services:
  - type: web
    name: comment-system-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.0.0
      - key: SERVER_URL
        value: https://comment-system-backend-7teb.onrender.com
